name: CI Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: GO vetting
      run: go vet ./...

    - name: GO test
      run: go test -v ./...
